<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="net04-PC" ignored="7" name="Default test" tests="1" failures="1" timestamp="15 Feb 2018 10:53:02 GMT" time="7.935" errors="0">
  <testcase name="verify_resto" time="0.548" classname="Test_Cases.Verify_dashboard">
    <failure type="javax.imageio.IIOException" message="Can&amp;apos;t read input file!">
      <![CDATA[javax.imageio.IIOException: Can't read input file!
	at javax.imageio.ImageIO.read(ImageIO.java:1301)
	at lib_methods.Comapre_images.compare_hideen_image(Comapre_images.java:88)
	at com.pageObject.Home.verify_restautants(Home.java:386)
	at Test_Cases.Verify_dashboard.verify_resto(Verify_dashboard.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_resto -->
  <testcase name="take_screenshot" time="0.0" classname="Test_Cases.Verify_dashboard">
    <ignored/>
  </testcase> <!-- take_screenshot -->
  <testcase name="verify_location" time="0.0" classname="Test_Cases.Verify_dashboard">
    <ignored/>
  </testcase> <!-- verify_location -->
  <testcase name="verify_rights" time="0.0" classname="Test_Cases.Verify_dashboard">
    <ignored/>
  </testcase> <!-- verify_rights -->
  <testcase name="verify_cart" time="0.0" classname="Test_Cases.Verify_dashboard">
    <ignored/>
  </testcase> <!-- verify_cart -->
  <testcase name="verify_quicklinks" time="0.0" classname="Test_Cases.Verify_dashboard">
    <ignored/>
  </testcase> <!-- verify_quicklinks -->
  <testcase name="verify_contact" time="0.0" classname="Test_Cases.Verify_dashboard">
    <ignored/>
  </testcase> <!-- verify_contact -->
  <testcase name="Headerlinks" time="0.0" classname="Test_Cases.Verify_dashboard">
    <ignored/>
  </testcase> <!-- Headerlinks -->
</testsuite> <!-- Default test -->
